version: '3'
services:
  frontend: 
    build:
      context: .
      dockerfile: compose/frontend/Dockerfile
      target: dev
    volumes:
      - ./aircash-frontend:/app
    ports:
      - '3000:3000'
 