name: Deploy Staging

on:
  workflow_run:
    workflows: ['Lint and Test']
    types: [completed]
    branches: master
  workflow_dispatch:

jobs:
  Build:
    runs-on: ubuntu-latest

    steps:
      - uses actions/checkout@v2
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 'lts/gallium'
      - name: Install Yarn
        run: npm install -g yarn
      - name: Install dependencies
        run: yarn
      - name: Build app
        run: yarn fe build
      - name: Copy built app to staging server
        uses: appleboy/scp-action@master
          host: ${{ secrets.STAGING_HOST_NAME }}
          username: ${{ secrets.STAGING_USER }}
          key: ${{ secrets.STAGING_SSH_KEY }}
          port: ${{ secrets.PORT }}
          source: "./aircash-frontend/.next"
          target: "./aircash"