name: Deploy Staging

on:
  workflow_run:
    workflows: ['Lint and Test']
    types: [completed]
    branches: master
  workflow_dispatch:

jobs:
  Build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 'lts/gallium'
      - name: Install Yarn
        run: npm install -g yarn
      - name: Install dependencies
        run: yarn ci:install
      - name: Build app
        run: yarn ci:build
      - name: Build app dist
        run: yarn ci:dist-build
      - name: Copy built app to staging server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.STAGING_HOST_NAME }}
          username: ${{ secrets.STAGING_SSH_USER }}
          key: ${{ secrets.STAGING_SSH_KEY }}
          port: ${{ secrets.STAGING_SSH_PORT }}
          source: "./dist"
          target: "/srv/microservices/aircash-staging/"