# This is a basic workflow to help you get started with Actions

name: Lint and Test

# Controls when the workflow will run
on:
  push:
    branches:
      -   master
  pull_request:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 'lts/gallium'
      - name: Install Yarn
        run: npm install -g yarn && yarn set version berry
      - name: Install dependencies
        run: yarn
      - name: Lint frontend
        run: yarn fe lint